<?php

/**
 * Aria S.p.A.
 * OPEN 2.0
 *
 *
 * @package    open20\amos\email
 * @category   CategoryName
 */

namespace open20\amos\emailmanager\assets;

use Yii;
use yii\web\AssetBundle;

/**
 * Class AmosMailAsset
 * @package open20\amos\emailmanager\assets
 */
class AmosMailAsset extends AssetBundle
{
    public $sourcePath = '@vendor/open20/amos-email-manager/src/assets/web';

    public $css = [
        'css/less/amos_mail.less'
    ];

    public $depends = [
    ];

    public function init()
    {
        $moduleL = Yii::$app->getModule('layout');
        if (!empty($moduleL)) {
            $this->depends [] = 'open20\amos\layout\assets\BaseAsset';
        } else {
            $this->depends [] = 'open20\amos\core\views\assets\AmosCoreAsset';
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

}